# Generated by Django 2.2.2 on 2019-06-26 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
